print("welcome pranam to our interface")
name = str(input("Enter your name: "))
age = int(input("Enter your age:"))
height = float(input("Enter your height:"))
number = int(input("Enter tor favourite number:"))
hobby = str(input("Enter your hobby: "))
color = str(input("Enter your favourite color: "))


print("your name: ",name," type: ",type(name))
print("memory adress: ",id(name))
print("your age: ",age," type: ",type(age))
print("memory adress: ",id(age))
print("your height: ",height," type: ",type(height))      
print("memory adress: ",id(height))
print("your favourite number: ",number," type: ",type(number))
print("memory adress: ",id(number))
print("your birth year is approximately:",2025-age)
print("based on your age: ",age)
print("your hobby: ",hobby," type: ",type(hobby))
print("memory adress: ",id(hobby))
print("your favourite color: ",color," type: ",type(color))
print("memory adress: ",id(color))
print ("Dhnyavad pranam for using our interface")
